In [2]:
import numpy as np

## Initialising an array

In [3]:
#1D Array
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
#2D Array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


## Getting Dimensions 

In [5]:
a.ndim

1

In [6]:
b.ndim

2

## Getting Shape, Type, Size, Total Size

In [7]:
a.shape

(3,)

In [8]:
b.shape

(2, 3)

In [9]:
#Type
print(a.dtype,b.dtype)
print(type(a),type(b))

int32 int32
<class 'numpy.ndarray'> <class 'numpy.ndarray'>


In [10]:
#Item Size
print(a.itemsize,b.itemsize)
print(a.size,b.size)

4 4
3 6


In [11]:
#Total Size (Size*Item Size)
print(a.nbytes,b.nbytes)

12 24


## Accessing, Changing rows columns and elements 

In [12]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [13]:
#Get specific element by [row,column]. Here lets extract 13
a[1,5]

13

In [14]:
#We can even use negative index for the same task
a[1,-2]

13

In [15]:
#Get a specific row. Here lets get the 1st row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [16]:
#Get a specific column. here lets get the 5th column
a[:,4]

array([ 5, 12])

In [17]:
#Start, Stop and Step Size indexing. Heres lets get the data from 2 to 6 with 2 stepsize
a[0,1::2]

array([2, 4, 6])

In [18]:
#Changing element
a[1,5] = 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


## 3-D Example

In [19]:
a = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(a)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [20]:
#Get 7 from this. Work your way from outside to inside
a[1,1,0]

7

## Initialising different types of arrays


In [21]:
#0 Array of 3 rows 2 columns of int type
a = np.zeros((3,2),dtype = 'int32')
print(a)

[[0 0]
 [0 0]
 [0 0]]


In [22]:
#One Array of 4 rows 2 columns of float type
b = np.ones((4,2),dtype='float32')
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [23]:
#Any other array where every element is equal. Here (4,3) is the size and 99 is the element
c = np.full((4,3),99)
print(c)

[[99 99 99]
 [99 99 99]
 [99 99 99]
 [99 99 99]]


In [24]:
#Random Numbers. Note that in random numbers we shouldn't pass the size as a tuple
a = np.random.rand(4,3)
print(a)

[[0.59209909 0.20537691 0.33158999]
 [0.49565123 0.98935325 0.81914625]
 [0.50801238 0.11822714 0.31530143]
 [0.34240813 0.76956082 0.40094465]]


In [25]:
#Random Integers within range 1 to 100 of size (4,3)
b = np.random.randint(1,100,size=(4,3))
print(b)

[[76 71 22]
 [53 90 29]
 [70 13 69]
 [66 92 82]]


In [26]:
#Identity Matrix
c = np.identity(3,dtype = 'int32')
print(c)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Matrix Multiplication and Determinant Finding

In [27]:
#Multiplication
a = np.random.randint(1,10,size=(2,3))
b = np.random.randint(1,5,size=(3,2))
print(a,'\n\n',b)

[[6 3 5]
 [8 5 8]] 

 [[1 3]
 [1 2]
 [1 2]]


In [28]:
c = np.matmul(a,b)
print(c)
d = a @ b #Another simple way for Matrix Multiplication
print(d)

[[14 34]
 [21 50]]
[[14 34]
 [21 50]]


In [29]:
#Finding Determinent
print(np.linalg.det(c))

-14.00000000000004


## Minimum, Maximum, SUm of an array along different axes

In [30]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

[[1 2 3]
 [4 5 6]]


In [31]:
#Finding the minimum of the array
np.min(a)

1

In [32]:
#Finding the maximum of the array
np.max(a)

6

In [33]:
#Finding the minimum along x-axis 
np.min(a,axis=0)

array([1, 2, 3])

In [34]:
#Finding the minimum along y-axis
np.min(a,axis=1)

array([1, 4])

In [35]:
#Finding the maximum along x-axis
np.max(a,axis=0)

array([4, 5, 6])

In [36]:
#Finding the maximum along y-axis
np.max(a,axis=1)

array([3, 6])

## Re-shaping Arrays


In [37]:
a = np.arange(1,11)
print(a,a.shape)

[ 1  2  3  4  5  6  7  8  9 10] (10,)


In [38]:
b = a.reshape(2,5)
print(b,b.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5)


## Vertical and Horizontal Stacking  

In [39]:
a = np.array([1,2,3])
b = np.array([4,5,6])
#Now, we want to stack a and b such that a comes first followed by b in vertical stacking
c = np.vstack([a,b])
print(c)

[[1 2 3]
 [4 5 6]]


In [40]:
#Now, we want to stack a and b such that b comes first followed by a and again b followed by a again in vertical stacking
c = np.vstack([b,a,b,a])
print(c)

[[4 5 6]
 [1 2 3]
 [4 5 6]
 [1 2 3]]


In [41]:
#Similarly for Horizontal Stack, we use np.hstack([a,b]) etc
h = np.hstack([a,b])
print(h)

[1 2 3 4 5 6]


## Vectorize Function

In [42]:
#For performing complex operations, we use vectorize functions rather than direct broadcasting
a = np.arange(1,16).reshape(3,5)
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [43]:
#Lets perform an operation element^2+2*element+10. Here, we created a funciton using lambda and then applied on each element
func = lambda i:pow(i,2)+(2*i)+10
fm = np.vectorize(func)
fm(a)

array([[ 13,  18,  25,  34,  45],
       [ 58,  73,  90, 109, 130],
       [153, 178, 205, 234, 265]])

In [44]:
#The usual way is as follows
print((pow(a,2)+(2*a)+10))

[[ 13  18  25  34  45]
 [ 58  73  90 109 130]
 [153 178 205 234 265]]


## Mean, Variance and Standard Deviation

In [45]:
'''First lets find the mean, variance and Standard Deviation using numpy calculation

Mean :- The average weights of all the values

Variance :- The degree or the amount of spreadness of the data points in a plane

Standard Deviaiton :- The amount of deviation from the mean to the data points'''

'First lets find the mean, variance and Standard Deviation using numpy calculation\n\nMean :- The average weights of all the values\n\nVariance :- The degree or the amount of spreadness of the data points in a plane\n\nStandard Deviaiton :- The amount of deviation from the mean to the data points'

In [46]:
a = np.array([1,5,6,5,8,0,2,8,5]).reshape(3,3)
print(a)

[[1 5 6]
 [5 8 0]
 [2 8 5]]


In [47]:
np.mean(a)

4.444444444444445

In [48]:
np.var(a)

7.358024691358025

In [49]:
np.std(a)

2.7125679146074897

## Getting Transpose of a Matrix

In [50]:
a = np.random.randint(1,11,size=(3,3))
print(a)

[[5 4 4]
 [5 6 6]
 [9 2 8]]


In [51]:
a.T

array([[5, 5, 9],
       [4, 6, 2],
       [4, 6, 8]])

## Calculating Diagonal of a Matrix and Trace

In [52]:
a = np.random.randint(1,11,size=(3,3))
print(a)

[[ 4  6  2]
 [ 4  1  1]
 [ 1  2 10]]


In [53]:
a.diagonal()

array([ 4,  1, 10])

In [54]:
#Trace is the sum of all diagonal elements
a.trace()

15

In [55]:
#This can also be done like this
a.diagonal().sum()
np.sum(a.diagonal())

15

## Another Way for Matrix Multiplication

In [56]:
a = np.random.randint(1,10,size=(2,3))
b = np.random.randint(1,5,size=(3,2))
print(a,'\n\n',b)

[[5 6 1]
 [8 6 5]] 

 [[2 2]
 [1 1]
 [2 3]]


In [57]:
print(np.matmul(a,b))

[[18 19]
 [32 37]]


In [58]:
#The other way is by using @ operator for multiplication
a @ b

array([[18, 19],
       [32, 37]])

## Inverting a Square Matrix

In [59]:
a = np.random.randint(1,11,size=(3,3))
print(a)

[[ 3 10  5]
 [ 1  7  3]
 [ 9  1  9]]


In [60]:
#Inverting a square matrix
print(np.linalg.inv(a))

[[ 1.2  -1.7  -0.1 ]
 [ 0.36 -0.36 -0.08]
 [-1.24  1.74  0.22]]


## Changing the Dimensions of the Array 

In [61]:
#By specifying the keyword ndmin=5 , we converted a 1D Array into a 5 dimensional array

#This can be used in real-life scenarios wherein only data of specific dimension can be passed in in which, we can use this.

a = np.array([1,2,3],ndmin=5)
print(a,a.ndim)

[[[[[1 2 3]]]]] 5


## Complex Datatype

In [62]:
#By specifying datatype as complex, we can cast integer to a complex number
a = np.array([1,2,3],dtype='complex')
print(a)

[1.+0.j 2.+0.j 3.+0.j]


## Converting an Array into a Matrix

In [63]:
a = np.array([1,2,3,4]).reshape(2,2)
print(type(a))
b = np.mat(a)
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.matrix'>


In [64]:
#We can even convert strings into a matrix easily
a = np.mat('1 2;3 4')
print(a)

[[1 2]
 [3 4]]


In [65]:
#Matrix is a subclass of Array while the converse if False
issubclass(np.ndarray,np.matrix)
issubclass(np.matrix,np.ndarray)

True

## Copy Function

In [66]:
#There are two types of copying in general which are Deep Copy and Shallow Copyin Python. lets look at them by example

In [67]:
x = np.array([1,2,3,4])
y = x

In [68]:
#Now, lets try to update any value in x and see if it is reflected in y as well
x[0] = 1251
print(x,y)
#We can clearly see that by updating the value of x, y changes too. This is called Shallow Copy wherein y doesnt create a
# new space but it just points to the location of x so if x changes, y changes too. We can aslo verify it by 'is' operator.

x is y

[1251    2    3    4] [1251    2    3    4]


True

In [69]:
z = np.copy(x)
x[1] = 121
print(x,z)
#As we can see here, even after changing the value of x, z doesnt change as it creates a new copy of values at different
#location. This is called as Deep Copy
x is z

[1251  121    3    4] [1251    2    3    4]


False

## FromFunction in Numpy

In [70]:
#This function is basically used to create an array based on a certain function by iterating over coordinates

In [71]:
np.fromfunction(lambda i,j: i*j ,(3,3),dtype='int32')

array([[0, 0, 0],
       [0, 1, 2],
       [0, 2, 4]])

## fromiter

In [72]:
#This function is basically used to create an array by using an iterable object

In [73]:
iterable = [pow(i,2) for i in range(1,6)]
iterable

[1, 4, 9, 16, 25]

In [74]:
#Fromiter takes 2 arguments, one is the iterable object and second is the datatype. Both are necessary to create an array

np.fromiter(iterable,int)

array([ 1,  4,  9, 16, 25])

## fromstring

In [75]:
#We can create a 1D Array based on a string by using a seperator

In [76]:
np.fromstring('123-234-456',sep='-')

array([123., 234., 456.])

In [77]:
s = '123 123243 234342'
np.fromstring(s,sep=' ')

array([1.23000e+02, 1.23243e+05, 2.34342e+05])

## arange

In [78]:
#The default range function in python cannot interpret floating point numbers as its starting point or end point
try:
    print(list(range(1.1,51,3)))
except:
    print('Range Error. Cannot use floating point numbers as indexes')

Range Error. Cannot use floating point numbers as indexes


In [79]:
#This is why we can use arange function in numpy to avoid this shortcoming
np.arange(5.2,16,3.3)

array([ 5.2,  8.5, 11.8, 15.1])

In [80]:
#It can even be used for negative direction as well
np.arange(-1000,-100,100)

array([-1000,  -900,  -800,  -700,  -600,  -500,  -400,  -300,  -200])

## linspace

In [81]:
#Let us look at the parameters of arange. They are start index, stop index and step size. So, arange returns an array of
#numbers from starrt index to stop index using step size


#But linspace works in a different way. The parameters of linspace are start index, stop index and number of values. So
# linspace returns an array with n equally spaced values between the start and stop index. Lets see an example


In [82]:
print(np.arange(1,10,5))
print(np.linspace(1,11,5))

[1 6]
[ 1.   3.5  6.   8.5 11. ]


## logspace 

In [83]:
#Returns numbers spaced evenly on a log scale for any base

In [84]:
np.logspace(2,3,4,base=10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

## Another way for diagonals in numpy

In [85]:
#reshape of (1,-1) is a default way of telling that -1 implies the size of the array by default. Just like index of a list
a = np.arange(16).reshape((4,-1))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [86]:
#Heres another way for getting the diagonal
np.diag(a)
#Here it has an optional parameter called k which can be an integer. Lets look the results based on that

array([ 0,  5, 10, 15])

In [87]:
print(np.diag(a,k=1))
print(np.diag(a,k=2))
#We can observe that as we change the value of k, it leaves k number of indexes and prints diagonal out of remaining

[ 1  6 11]
[2 7]


In [88]:
#If we call the diagonal function inside diagonal function, it reconstructs the matrix with elements as diagonals
b = np.diag(a)
print(b)
print(np.diag(b))

[ 0  5 10 15]
[[ 0  0  0  0]
 [ 0  5  0  0]
 [ 0  0 10  0]
 [ 0  0  0 15]]


## Tri Function

In [89]:
#This function returns an array with ones at and below the diagonals and zeros elsewhere
np.tri(3,5,0,dtype=int)
#Here 3 is number of rows, 5 is no of columns and 0 is value of k

array([[1, 0, 0, 0, 0],
       [1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0]])

### Tril Function

In [90]:
#This function when invoked, retains all the data present in the lower triangle of the array and keeps 0s in other places.
a = np.random.randint(1,11,(3,3))
a

array([[ 3,  4,  7],
       [ 4,  6, 10],
       [ 6,  3,  6]])

In [91]:
np.tril(a,0)
#Here, 0 refers to the value of k and every data above the diagonal or the upper data is replaced by 0s

array([[3, 0, 0],
       [4, 6, 0],
       [6, 3, 6]])

In [92]:
np.tril(a,-1)
#Here k is -1 so leaving aside the last column and first row, we get diagonal as 2,3 so eveeything above that is 0.

array([[0, 0, 0],
       [4, 0, 0],
       [6, 3, 0]])

### Triu Function

In [93]:
#This function when invoked, retains all the data present in the upper triangle of the array and keeps 0s in other places.
a = np.random.randint(1,11,(3,3))
a

array([[3, 5, 4],
       [5, 9, 4],
       [6, 5, 8]])

In [94]:
np.triu(a,0)
#Here, 0 refers to the value of k and every data above the diagonal or the upper data is replaced by 0s

array([[3, 5, 4],
       [0, 9, 4],
       [0, 0, 8]])

In [95]:
np.triu(a,-1)
#Here k is -1 so leaving aside the last column and first row, we get diagonal as 5,3 so everything below that is 0.

array([[3, 5, 4],
       [5, 9, 4],
       [0, 5, 8]])

## Randn Function

In [96]:
#randn function generates the data similar to rand function but it follows 'standard normal' distribution.
#Standard Normal Distribution is the data in which mean =0 and standard deviation =1
a = np.random.randn(4,4)
print(a)

[[-1.1019371  -0.70330165  1.51321378 -0.15743886]
 [ 0.09686842  0.87228423  0.53523221  0.1886438 ]
 [-0.18354316  0.42970017  1.14625729  0.33393464]
 [ 1.04781235  0.47977073  0.06496617  0.5451251 ]]


## Problems

In [127]:
#Write a NumPy program to generate five random numbers from the normal distribution.

np.random.randn(1,5)

array([[ 0.7459263 ,  0.79669254, -1.07319951,  0.38259845, -1.68020119]])

In [133]:
#Write a NumPy program to generate six random integers between 10 and 30

np.random.randint(10,30,(1,6))

array([[14, 28, 16, 24, 24, 28]])

In [136]:
#Write a NumPy program to create a 3x3x3 array with random values

np.random.rand(3,3,3)

array([[[ 0.62486547,  0.70975376,  0.72978097],
        [ 0.44345745,  0.50268658,  0.66908506],
        [ 0.03187394,  0.24163107,  0.21663359]],

       [[ 0.11803243,  0.10086249,  0.4811287 ],
        [ 0.04316692,  0.47706129,  0.01564123],
        [ 0.56756949,  0.2318128 ,  0.02148702]],

       [[ 0.6435234 ,  0.45789745,  0.20169975],
        [ 0.0409638 ,  0.50922682,  0.4924422 ],
        [ 0.05828754,  0.06919619,  0.14962513]]])

In [137]:
#Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

a = np.random.rand(5,5)
print(f'The array is {a} \n\n  The minimum value is {np.min(a)} \n\n The maximum value is {np.max(a)}')

The array is [[ 0.19355593  0.95229664  0.27565393  0.35973573  0.61067894]
 [ 0.52756178  0.2911696   0.81211015  0.44001987  0.83492591]
 [ 0.3410721   0.33652625  0.0290134   0.74621117  0.7114234 ]
 [ 0.92509138  0.09366675  0.83486541  0.82885503  0.85538792]
 [ 0.14498996  0.08078858  0.43025702  0.25668131  0.28747967]] 

  The minimum value is 0.029013396682562864 

 The maximum value is 0.952296640100165


In [146]:
#Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable

a = np.random.rand(10,4)
b = a[0:5,:]
print(f'{a} \n\n {b}')


[[ 0.80491379  0.87022999  0.47494955  0.03306125]
 [ 0.65752081  0.21571274  0.19354994  0.98693041]
 [ 0.50664923  0.32174935  0.0814944   0.74910806]
 [ 0.05760512  0.01634946  0.97259017  0.97343509]
 [ 0.06016616  0.42658453  0.45887377  0.05833462]
 [ 0.76998184  0.48094676  0.38965118  0.68042382]
 [ 0.30710323  0.75913213  0.11456925  0.67177481]
 [ 0.13752253  0.33065027  0.95560852  0.01050648]
 [ 0.29413574  0.24342274  0.1241378   0.15903404]
 [ 0.3760812   0.03364552  0.6133067   0.79257986]] 

 [[ 0.80491379  0.87022999  0.47494955  0.03306125]
 [ 0.65752081  0.21571274  0.19354994  0.98693041]
 [ 0.50664923  0.32174935  0.0814944   0.74910806]
 [ 0.05760512  0.01634946  0.97259017  0.97343509]
 [ 0.06016616  0.42658453  0.45887377  0.05833462]]


In [150]:
#Write a NumPy program to shuffle numbers between 0 and 10 (inclusive)
a = np.arange(1,11)
print(a,'\n\n',np.random.permutation(a))

[ 1  2  3  4  5  6  7  8  9 10] 

 [ 7  4  9 10  5  2  3  1  8  6]


In [164]:
#Write a NumPy program to normalize a 3x3 random matrix
nor = lambda i: (i-mini)/(maxi-mini)
vec = np.vectorize(nor)
a = np.random.rand(3,3)
mini,maxi = np.min(a),np.max(a)
print(a,'\n\n',vec(a))

[[ 0.61473069  0.7939148   0.27306782]
 [ 0.67798851  0.23427961  0.7670997 ]
 [ 0.05348997  0.63326734  0.3383215 ]] 

 [[ 0.75799825  1.          0.29655657]
 [ 0.84343274  0.24417014  0.96378417]
 [ 0.          0.7830334   0.38468663]]


In [167]:
#Write a NumPy program to create a random vector of size 10 and sort it

a = np.random.rand(10)
print(a,'\n\n',np.sort(a))

[ 0.84951487  0.22593124  0.37729008  0.83046067  0.93376256  0.38569905
  0.96785062  0.02911721  0.53235297  0.15075413] 

 [ 0.02911721  0.15075413  0.22593124  0.37729008  0.38569905  0.53235297
  0.83046067  0.84951487  0.93376256  0.96785062]


In [181]:
#Print Range Between 1 To 15 and show 4 integers random numbers

np.random.randint(1,15,4)

array([4, 9, 7, 5])

In [183]:
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
a = np.random.randint(1,high=500000, size=(20, 5))
a

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [196]:
#What is the average value of the second column 
print(round(np.mean(a[:,1]),2))

214895.8


In [200]:
#What is the average value of the first 5 rows of the third and fourth columns?
print(np.mean(a[0:4,3:5]))

225231.25


In [202]:
#Iterate through each element in a 3x3 array
a = np.random.randint(1,11,(3,3))
print(a,'\n\n')
for i in a:
    for j in i:
        print(j)

[[8 6 3]
 [8 6 1]
 [5 3 3]] 


8
6
3
8
6
1
5
3
3
